import fs from "fs/promises";
import path from "path";
import Head from "next/head";
import { Inter } from "@next/font/google";
import { GetStaticProps } from "next";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

interface PropsType {
  products: {
    id: string;
    title: string;
  }[];
}
export default function Home(props: PropsType) {
  const { products } = props;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {products.map((product) => (
          <li key={product.id}>
            <Link href={`/products/${product.id}`}>{product.title}</Link>
          </li>
        ))}
      </ul>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const filePath = path.join(process.cwd(), "data", "dummy-backend.json");
  const jsonData = await fs.readFile(filePath);
  const data = JSON.parse(jsonData.toString());

  return {
    props: {
      products: data.products,
    },

    revalidate: 10,
  };
};
